---
- hosts: all
  tasks:

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
    - vim
    - htop
    - iotop
    - apt-file
    - autoconf
    - mc
    - bind9
    - dnsutils
    - isc-dhcp-server
    - iptables-persistent
    - tcpdump
    - nmap
    - screen
    - openvpn
    - easy-rsa
    - ruby
    - ruby-dev
    - libffi-dev
    - squid
    - zip
    - git
    - ntp
    - unattended-upgrades
    - bridge-utils
    - telnet
    - rng-tools
    - mtr
    - lftp

  - name: configure networking
    template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0644
    with_items:
    - etc/network/interfaces
    - etc/dhcpcd.conf
    - etc/default/isc-dhcp-server
    - etc/dhcp/dhcpd.conf
    - etc/iptables/rules.v4
    - etc/bind/db.rpz
    - etc/bind/named.conf.local
    - etc/bind/named.conf.options
    - etc/ssh/sshd_config
    - etc/resolvconf.conf
    - etc/rc.local
    tags:
    - networking

  - name: other configs
    template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0644
    with_items:
    - root/.screenrc

  - name: configure sysctl
    sysctl: name=net.ipv4.ip_forward value=1 sysctl_file=/etc/sysctl.d/10-firewall.conf sysctl_set=yes

  - name: manage openvpn group
    group: name=openvpn system=yes state=present

  - name: manage openvpn user account
    user: name=openvpn group=openvpn append=yes home=/var/openvpn shell=/usr/sbin/nologin system=yes state=present

  - name: enable / start services
    service: name={{ item }} enabled=yes state=started
    with_items:
    - isc-dhcp-server
    - bind9
    - openvpn

  - name: set generic aliases for all users
    template: src=etc/profile.d/aliases.sh dest=/etc/profile.d/aliases.sh mode=0644 owner=root

  - name: configure Squid
    template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0600
    with_items:
    - etc/squid/squid.conf

  - name: install Sensu gem
    gem: name=sensu user_install=yes state=present

  - name: create Sensu dirs
    file: path={{ item }} state=directory
    with_items:
    - /etc/sensu/conf.d
    - /etc/sensu/extensions
    - /var/log/sensu

  - name: configure Sensu
    template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0644
    with_items:
    - etc/sensu/conf.d/client.json
    - etc/sensu/conf.d/transport.json
    - etc/sensu/conf.d/rabbitmq.json
    - etc/sensu/extensions/system-profile.rb
    - etc/sensu/conf.d/system_profile.json
    - etc/sensu/conf.d/extensions.json
    - etc/sensu/conf.d/metrics.json
    tags:
    - sensu-config

  - name: Create a directory if it does not exist
    file: path=/etc/sensu/plugins state=directory mode=0755
    tags:
    - sensu-config

  - name: Sensu plugins
    template:  src={{ item }} dest=/{{ item }} owner=root group=root mode=755
    with_items:
    - etc/sensu/plugins/metrics-disk-usage.rb
    - etc/sensu/plugins/metrics-memory-percent.rb
    - etc/sensu/plugins/metrics-temperature-rpi.rb
    tags:
    - sensu-config

  - name: auto-start Sensu
    lineinfile:
      dest: /etc/rc.local
      line: '/root/.gem/ruby/2.3.0/bin/sensu-client -e /etc/sensu/extensions -l /dev/null &'
      state: present
      insertbefore: 'exit 0'
    tags:
    - sensu-config

  - name: install sensu-plugin gem
    gem:
      executable: /usr/bin/gem2.3
      name: sensu-plugin
      state: present
    tags:
    - sensu-config

# TODO: logrotate sensu

  - name: traffic control
    template: src=usr/local/sbin/trafcon dest=/usr/local/sbin/trafcon owner=root group=root mode=0755
    tags:
    - traffic-control

  - name: traffic control on
    cron:
      name: traffic control on
      minute: "0"
      hour: "23"
      job: "/usr/local/sbin/trafcon on"
      state: present
    tags:
    - traffic-control

  - name: traffic control off Mon-Fri
    cron:
      name: traffic control off Mon-Fri
      minute: "0"
      hour: "9"
      weekday: "mon,tue,wed,thu,fri"
      job: "/usr/local/sbin/trafcon off"
      state: present
    tags:
    - traffic-control

  - name: traffic control off Sat-Sun
    cron:
      name: traffic control off Sat-Sun
      minute: "0"
      hour: "10"
      weekday: "sat,sun"
      job: "/usr/local/sbin/trafcon off"
      state: present
    tags:
    - traffic-control
