#!/usr/bin/env bash

if [ $# -ne 1 ]; then
	echo "Usage: $0 <on|off>"
	exit 1
fi

ipt="/sbin/iptables"
lan="192.168.1.0/24"

macs=()
# predator
macs+=( "48:f1:7f:c2:ab:69" )
# h1 phone
macs+=( "88:5f:e8:70:37:45" )
# tic watch
macs+=( "30:95:e3:32:73:d2" )
# server
macs+=( "38:2c:4a:ba:b1:6a" )
# media
macs+=( "74:d4:35:9f:1d:ee" )
# weather pi
macs+=( "b8:27:eb:77:ee:23" )
# linksys tower
macs+=( "24:f5:a2:84:5d:e2" )
# ps4
macs+=( "60:5b:b4:ac:1f:8b" )
# m-laptop
macs+=( "cc:d9:ac:29:90:af" )
# m-phone
macs+=( "c6:60:22:69:d4:f1" )
# chromecast
macs+=( "3c:8d:20:05:0a:a3" )
# google assistant speaker
macs+=( "6c:5a:b5:54:e5:9e" )
# v phone
macs+=( "08:cc:27:41:22:0a" )
# a phone
macs+=( "dc:bf:e9:dc:85:9b" )
# wifi extender
macs+=( "c4:41:1e:8c:da:65" )


if [ "on" == $1 ]; then
	$ipt -F traffic-control
	for m in ${macs[@]}; do
		$ipt -A traffic-control -m mac --mac-source ${m} -j ACCEPT
	done
	$ipt -A traffic-control -s ${lan} -j LOG -m limit --limit 1/s --limit-burst 5 --log-prefix "iptables "
	$ipt -A traffic-control -s ${lan} -j DROP
	exit
fi

if [ "off" == $1 ]; then
	$ipt -F traffic-control
	exit
fi

echo "Usage: $0 <on|off>"
exit 1
